name: project_bist
description: A new Flutter project.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.1.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  one_context: ^2.1.0
  flutter_svg: ^2.0.8
  flutter_riverpod: ^2.4.0
  url_launcher: ^6.2.1
  flutter_inappwebview: ^5.8.0
  dio: ^5.3.2
  pretty_dio_logger: ^1.3.1
  get: ^4.6.5
  email_validator: ^2.1.17
  carousel_slider: ^4.2.1
  intl: ^0.18.1
  pinput: ^3.0.1
  intl_phone_field: ^3.2.0
  permission_handler: ^10.0.0
  google_fonts: ^4.0.4
  face_camera: ^0.0.8
  dotted_line: ^3.2.2
  flutter_lints: ^3.0.1
  get_it: ^7.6.4
  hive: ^2.2.3
  flutter_screenutil: ^5.9.0
  el_tooltip: ^2.0.0
  file_picker: ^6.1.1
  datepicker_dropdown: ^0.0.9
  bot_toast: ^4.1.3
  hive_flutter: ^1.1.0
  hive_generator: ^2.0.1
  flutter_secure_storage: ^9.0.0
  riverpod_annotation: ^2.3.3
  flutter_spinkit: ^5.2.0
  cloudinary_sdk: ^5.0.0+1
  image_picker: ^1.0.6
  cloudinary_url_gen: ^1.4.4
  connectivity_plus: ^5.0.2
  cloudinary_flutter: ^1.2.0
  google_mlkit_commons:
  google_mlkit_face_detection:
  cached_network_image: ^3.3.1
  timeago: ^3.6.0
  pdf: ^3.10.7
  redacted: ^1.0.11
  fade_shimmer: ^2.2.0
  ripple_wave: ^0.1.3
  password_policy: ^1.2.0
  socket_io_client: ^2.0.3
  flutter_local_notifications: ^9.9.1
#  firebase_core: ^2.27.0
#  firebase_messaging: ^14.7.19
#  firebase_analytics: ^10.8.9
#  flutter_file_downloader: ^1.2.1
  firebase_core:
  firebase_messaging:
  firebase_analytics:
  flutter_file_downloader:
  http: ^1.2.0
  open_file: ^3.5.10


dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^2.4.7
  riverpod_generator: ^2.3.9
  flutter_launcher_icons: "^0.13.1"

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/images/app_icon.png"
  min_sdk_android: 21
  flutter_lints: ^2.0.0

flutter:

  uses-material-design: true

  assets:
    - assets/data/
    - assets/gifs/
    - assets/icons/
    - assets/icons/chat_attachment.png
    - assets/icons/chat_download.png
    - assets/icons/drawer/
    - assets/icons/edit_work_icon.png
    - assets/icons/nav_notification.png
    - assets/images/
    - assets/svgs/




  fonts:
    - family: MontserratAlternates-Black
      fonts:
        - asset: assets/fonts/montserrat_alternates/MontserratAlternates-Black.ttf
    - family: MontserratAlternates-Bold
      fonts:
        - asset: assets/fonts/montserrat_alternates/MontserratAlternates-Bold.ttf
    - family: MontserratAlternates-ExtraBold
      fonts:
        - asset: assets/fonts/montserrat_alternates/MontserratAlternates-ExtraBold.ttf
    - family: MontserratAlternates-ExtraLight
      fonts:
        - asset: assets/fonts/montserrat_alternates/MontserratAlternates-ExtraLight.ttf
    - family: MontserratAlternates-Light
      fonts:
        - asset: assets/fonts/montserrat_alternates/MontserratAlternates-Light.ttf
    - family: MontserratAlternates-Medium
      fonts:
        - asset: assets/fonts/montserrat_alternates/MontserratAlternates-Medium.ttf
    - family: MontserratAlternates-Regular
      fonts:
        - asset: assets/fonts/montserrat_alternates/MontserratAlternates-Regular.ttf
    - family: MontserratAlternates-SemiBold
      fonts:
        - asset: assets/fonts/montserrat_alternates/MontserratAlternates-SemiBold.ttf
    - family: MontserratAlternates-Thin
      fonts:
        - asset: assets/fonts/montserrat_alternates/MontserratAlternates-Thin.ttf
    - family: Nunito-Black
      fonts:
        - asset: assets/fonts/nunito/Nunito-Black.ttf
    - family: Nunito-Bold
      fonts:
        - asset: assets/fonts/nunito/Nunito-Bold.ttf
    - family: Nunito-ExtraBold
      fonts:
        - asset: assets/fonts/nunito/Nunito-ExtraBold.ttf
    - family: Nunito-ExtraLight
      fonts:
        - asset: assets/fonts/nunito/Nunito-ExtraLight.ttf
    - family: Nunito-Light
      fonts:
        - asset: assets/fonts/nunito/Nunito-Light.ttf
    - family: Nunito-Medium
      fonts:
        - asset: assets/fonts/nunito/Nunito-Medium.ttf
    - family: Nunito-Regular
      fonts:
        - asset: assets/fonts/nunito/Nunito-Regular.ttf
    - family: Nunito-SemiBold
      fonts:
        - asset: assets/fonts/nunito/Nunito-SemiBold.ttf