/// Generated file. Do not edit.
/// This file is generated by the iFlutter

// ignore_for_file: constant_identifier_names
// ignore_for_file: lines_longer_than_80_chars
class AssetsRes {
  AssetsRes._();

  static const String PLUGIN_NAME = 'project_bist';
  static const String PLUGIN_VERSION = '1.0.0+1';
  static const String CHAT_ATTACHMENT = 'assets/icons/chat_attachment.png';
  static const String CHAT_DOWNLOAD = 'assets/icons/chat_download.png';
  static const String EDIT_WORK_ICON = 'assets/icons/edit_work_icon.png';
  static const String NAV_NOTIFICATION = 'assets/icons/nav_notification.png';
}
