/// Generated file. Do not edit.
/// This file is generated by the iFlutter

// ignore_for_file: constant_identifier_names
// ignore_for_file: lines_longer_than_80_chars
class FontRes {
  FontRes._();

  static const String MONTSERRATALTERNATES_BLACK = 'MontserratAlternates-Black';
  static const String MONTSERRATALTERNATES_BOLD = 'MontserratAlternates-Bold';
  static const String MONTSERRATALTERNATES_EXTRABOLD = 'MontserratAlternates-ExtraBold';
  static const String MONTSERRATALTERNATES_EXTRALIGHT = 'MontserratAlternates-ExtraLight';
  static const String MONTSERRATALTERNATES_LIGHT = 'MontserratAlternates-Light';
  static const String MONTSERRATALTERNATES_MEDIUM = 'MontserratAlternates-Medium';
  static const String MONTSERRATALTERNATES_REGULAR = 'MontserratAlternates-Regular';
  static const String MONTSERRATALTERNATES_SEMIBOLD = 'MontserratAlternates-SemiBold';
  static const String MONTSERRATALTERNATES_THIN = 'MontserratAlternates-Thin';
  static const String NUNITO_BLACK = 'Nunito-Black';
  static const String NUNITO_BOLD = 'Nunito-Bold';
  static const String NUNITO_EXTRABOLD = 'Nunito-ExtraBold';
  static const String NUNITO_EXTRALIGHT = 'Nunito-ExtraLight';
  static const String NUNITO_LIGHT = 'Nunito-Light';
  static const String NUNITO_MEDIUM = 'Nunito-Medium';
  static const String NUNITO_REGULAR = 'Nunito-Regular';
  static const String NUNITO_SEMIBOLD = 'Nunito-SemiBold';
}
